FROM node:18-alpine

WORKDIR /app

# Copiar apenas os arquivos de dependências primeiro
COPY backend/package*.json ./

# Instalar dependências
RUN npm install
COPY backend/ .

EXPOSE 8000
CMD ["npm", "start"]
