FROM node:18-alpine

WORKDIR /app

# Copiar apenas os arquivos de dependências primeiro
COPY frontend/package*.json ./

# Instalar dependências
RUN npm install
COPY frontend/ .

EXPOSE 3000
CMD ["npm", "run", "serve"]